const KEY = 'carepoint-hospital-v1';
const seed = {
  patients:[
    {id:'PT-1048',name:'Olivia Bennett',age:34,gender:'Female',phone:'+1 (306) 555-0142',email:'olivia.b@email.com',department:'Cardiology',doctor:'Dr. James Wilson',date:'2025-03-18',status:'Admitted',blood:'O+'},
    {id:'PT-1047',name:'Noah Williams',age:52,gender:'Male',phone:'+1 (306) 555-0187',email:'noah.w@email.com',department:'Neurology',doctor:'Dr. Sarah Chen',date:'2025-03-18',status:'Outpatient',blood:'A+'},
    {id:'PT-1046',name:'Emma Thompson',age:28,gender:'Female',phone:'+1 (306) 555-0119',email:'emma.t@email.com',department:'Pediatrics',doctor:'Dr. Michael Reed',date:'2025-03-17',status:'Discharged',blood:'B+'},
    {id:'PT-1045',name:'Liam Anderson',age:45,gender:'Male',phone:'+1 (306) 555-0164',email:'liam.a@email.com',department:'Orthopedics',doctor:'Dr. James Wilson',date:'2025-03-17',status:'Admitted',blood:'AB+'},
    {id:'PT-1044',name:'Sophia Martinez',age:63,gender:'Female',phone:'+1 (306) 555-0126',email:'sophia.m@email.com',department:'Cardiology',doctor:'Dr. Sarah Chen',date:'2025-03-16',status:'Outpatient',blood:'O-'},
    {id:'PT-1043',name:'Ethan Davis',age:39,gender:'Male',phone:'+1 (306) 555-0192',email:'ethan.d@email.com',department:'Neurology',doctor:'Dr. Michael Reed',date:'2025-03-16',status:'Admitted',blood:'A-'}
  ],
  appointments:[
    {id:'AP-2301',patient:'Olivia Bennett',patientId:'PT-1048',doctor:'Dr. James Wilson',department:'Cardiology',date:'2025-03-19',time:'09:00',type:'Follow-up',status:'Confirmed'},
    {id:'AP-2302',patient:'Noah Williams',patientId:'PT-1047',doctor:'Dr. Sarah Chen',department:'Neurology',date:'2025-03-19',time:'09:30',type:'Consultation',status:'Confirmed'},
    {id:'AP-2303',patient:'Emma Thompson',patientId:'PT-1046',doctor:'Dr. Michael Reed',department:'Pediatrics',date:'2025-03-19',time:'10:00',type:'Check-up',status:'Pending'},
    {id:'AP-2304',patient:'Liam Anderson',patientId:'PT-1045',doctor:'Dr. James Wilson',department:'Orthopedics',date:'2025-03-19',time:'10:30',type:'Follow-up',status:'Confirmed'},
    {id:'AP-2305',patient:'Sophia Martinez',patientId:'PT-1044',doctor:'Dr. Sarah Chen',department:'Cardiology',date:'2025-03-19',time:'11:00',type:'Consultation',status:'Cancelled'}
  ],
  staff:[
    {id:'ST-010',name:'Dr. James Wilson',role:'Cardiologist',department:'Cardiology',email:'j.wilson@citygeneral.org',phone:'+1 (306) 555-0101',status:'On duty'},
    {id:'ST-011',name:'Dr. Sarah Chen',role:'Neurologist',department:'Neurology',email:'s.chen@citygeneral.org',phone:'+1 (306) 555-0102',status:'On duty'},
    {id:'ST-012',name:'Dr. Michael Reed',role:'Pediatrician',department:'Pediatrics',email:'m.reed@citygeneral.org',phone:'+1 (306) 555-0103',status:'On duty'},
    {id:'ST-013',name:'Dr. Aisha Patel',role:'Head Nurse',department:'Emergency',email:'a.patel@citygeneral.org',phone:'+1 (306) 555-0104',status:'On leave'},
    {id:'ST-014',name:'Dr. Robert Kim',role:'Surgeon',department:'Orthopedics',email:'r.kim@citygeneral.org',phone:'+1 (306) 555-0105',status:'On duty'}
  ],
  wards:[{name:'General Ward',type:'Inpatient',total:48,occupied:36},{name:'ICU',type:'Critical care',total:20,occupied:16},{name:'Pediatrics',type:'Inpatient',total:32,occupied:21},{name:'Maternity',type:'Specialty',total:28,occupied:18},{name:'Surgery',type:'Post-op',total:24,occupied:20},{name:'Emergency',type:'Acute care',total:18,occupied:13}],
  lab:[{id:'LB-5001',patient:'Olivia Bennett',test:'Complete blood count',ordered:'2025-03-18',priority:'Routine',status:'In progress'},{id:'LB-5002',patient:'Noah Williams',test:'Metabolic panel',ordered:'2025-03-18',priority:'Urgent',status:'Pending'},{id:'LB-5003',patient:'Liam Anderson',test:'X-ray · Left knee',ordered:'2025-03-17',priority:'Routine',status:'Completed'},{id:'LB-5004',patient:'Sophia Martinez',test:'Lipid profile',ordered:'2025-03-17',priority:'Routine',status:'Completed'}],
  pharmacy:[{name:'Amoxicillin 500mg',category:'Antibiotic',stock:128,reorder:40,expiry:'2026-08-30'},{name:'Paracetamol 500mg',category:'Analgesic',stock:24,reorder:50,expiry:'2027-02-12'},{name:'Metformin 850mg',category:'Antidiabetic',stock:92,reorder:30,expiry:'2026-11-18'},{name:'Salbutamol inhaler',category:'Respiratory',stock:16,reorder:25,expiry:'2026-06-04'},{name:'Omeprazole 20mg',category:'Gastrointestinal',stock:74,reorder:30,expiry:'2027-01-21'}],
  invoices:[{id:'INV-0088',patient:'Olivia Bennett',date:'2025-03-18',amount:1240,status:'Unpaid'},{id:'INV-0087',patient:'Noah Williams',date:'2025-03-18',amount:380,status:'Paid'},{id:'INV-0086',patient:'Emma Thompson',date:'2025-03-17',amount:215,status:'Paid'},{id:'INV-0085',patient:'Liam Anderson',date:'2025-03-17',amount:2860,status:'Unpaid'},{id:'INV-0084',patient:'Sophia Martinez',date:'2025-03-16',amount:540,status:'Overdue'}],
  activity:[{icon:'♙',tone:'i-blue',text:'<b>Olivia Bennett</b> was admitted to Cardiology',time:'10 min ago'},{icon:'▦',tone:'i-green',text:'New appointment booked with <b>Dr. Sarah Chen</b>',time:'32 min ago'},{icon:'⚗',tone:'i-orange',text:'Lab results ready for <b>Liam Anderson</b>',time:'1 hour ago'},{icon:'＄',tone:'i-purple',text:'Payment received from <b>Noah Williams</b>',time:'2 hours ago'}],
  settings:{hospital:'City General Hospital',email:'admin@citygeneral.org',phone:'+1 (306) 555-0100',address:'123 Health Avenue, Regina, SK',currency:'CAD ($)'}
};
let db; try{db=JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{db=structuredClone(seed)}
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=n=>String(n||'').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const currency=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(n);
const badge=s=>{let k=/admit|duty|paid|completed|confirmed/i.test(s)?'green':/progress|outpatient|pending|urgent/i.test(s)?'blue':/cancel|overdue|leave|low/i.test(s)?'red':/discharged|routine/i.test(s)?'gray':'orange';return `<span class="badge badge-${k}">${esc(s)}</span>`};
const rowPerson=(name,sub='')=>`<div class="person-cell"><div class="avatar avatar-purple">${esc(initials(name))}</div><span><span class="person-name">${esc(name)}</span>${sub?`<span class="person-sub">${esc(sub)}</span>`:''}</span></div>`;
const heading=(title,desc,actions='')=>`<div class="page-heading"><div><div class="eyebrow">CITY GENERAL HOSPITAL</div><h1>${title}</h1><p>${desc}</p></div><div class="heading-actions">${actions}</div></div>`;
const button=(label,act,primary=false,icon='')=>`<button class="button ${primary?'button-primary':''}" data-action="${act}">${icon?`<span class="plus">${icon}</span>`:''}${label}</button>`;
const searchBox=(placeholder='Search...')=>`<label class="toolbar-search"><span>⌕</span><input type="search" placeholder="${placeholder}" data-table-search /></label>`;
function toast(message){const n=document.createElement('div');n.className='toast';n.textContent=message;$('#toast-region').append(n);setTimeout(()=>n.remove(),2800)}
const navViews=['overview','patients','appointments','staff','wards','laboratory','pharmacy','billing','reports','settings'];
function setView(view){if(!navViews.includes(view))view='overview';location.hash=view;render(view);$$('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.view===view));$('#breadcrumb-current').textContent=({overview:'Overview',patients:'Patients',appointments:'Appointments',staff:'Medical staff',wards:'Wards & beds',laboratory:'Laboratory',pharmacy:'Pharmacy',billing:'Billing',reports:'Reports',settings:'Settings'})[view];$('#sidebar').classList.remove('open')}
function stats(items){return `<div class="grid stats-grid">${items.map(x=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${x[4]}">${x[5]}</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot"><span class="trend ${x[3]?'down':''}">${x[2]}</span>${x[3]?'vs last month':'from last month'}</div></div>`).join('')}</div>`}
function overview(){let s=stats([['Total Patients',db.patients.length+1240,'↑ 12.8%',false,'i-blue','♙'],['Appointments Today',db.appointments.filter(a=>a.status!=='Cancelled').length+38,'↑ 8.2%',false,'i-green','▦'],['Available Beds',db.wards.reduce((a,w)=>a+w.total-w.occupied,0),'↓ 3.1%',true,'i-orange','▤'],['Monthly Revenue',currency(48250),'↑ 14.6%',false,'i-purple','＄']]);return `${heading('Good morning, Alex 👋',`Here's what's happening at your hospital today. <span class="muted">Tuesday, March 18, 2025</span>`,`${button('Export report','export',false,'↓')}${button('New appointment','new-appointment',true,'+')}`)}${s}<div class="grid dashboard-grid"><div class="card chart-card"><div class="card-header"><div><h2 class="card-title">Patient overview</h2><p class="card-subtitle">Patient admissions and discharges</p></div><select class="period-select" id="chart-period"><option>Last 7 days</option><option>Last 30 days</option><option>Last 12 months</option></select></div><div class="chart-wrap"><span class="chart-tooltip">Admissions & discharges</span><canvas id="overview-chart" aria-label="Admissions and discharges chart"></canvas></div><div class="chart-legend"><span><i class="legend-dot legend-blue"></i>Admissions</span><span><i class="legend-dot legend-green"></i>Discharges</span></div></div><div class="card activity-card"><div class="card-header"><div><h2 class="card-title">Recent activity</h2><p class="card-subtitle">Latest updates across departments</p></div><button class="small-action" data-action="activity">View all</button></div><div class="activity-list">${db.activity.slice(0,4).map(a=>`<div class="activity-item"><span class="activity-mark ${a.tone}">${a.icon}</span><span class="activity-copy">${a.text}</span><span class="activity-time">${a.time}</span></div>`).join('')}</div></div></div><div class="grid lower-grid"><div class="card table-card"><div class="table-heading"><div><h2 class="card-title">Recent patients</h2><p class="card-subtitle">Patients recently added to the system</p></div><a class="table-link" href="#patients">View all →</a></div>${patientTable(db.patients.slice(0,5),false)}</div><div class="card department-card"><div class="card-header"><div><h2 class="card-title">Department overview</h2><p class="card-subtitle">Occupancy across departments</p></div><button class="small-action" data-action="wards">Details</button></div>${[['Emergency',82,'i-blue'],['Cardiology',68,'i-green'],['Neurology',54,'i-purple'],['Pediatrics',41,'i-orange']].map(d=>`<div class="department-row"><span class="department-icon ${d[2]}">✚</span><span class="department-name">${d[0]}</span><span class="department-value">${d[1]}%</span></div><div class="progress"><span style="width:${d[1]}%;background:${d[2]==='i-blue'?'#5b82e7':d[2]==='i-green'?'#34b48a':d[2]==='i-purple'?'#917bd5':'#e8a64c'}"></span></div>`).join('')}</div></div>`}
function patientTable(items,actions=true){if(!items.length)return `<div class="empty-state"><div class="empty-icon">♙</div>No patients match your search.</div>`;return `<div class="table-scroll"><table class="data-table"><thead><tr><th>Patient</th><th>Patient ID</th><th>Department</th><th>Doctor</th><th>Visit date</th><th>Status</th>${actions?'<th></th>':''}</tr></thead><tbody>${items.map(p=>`<tr data-search-row="${esc([p.name,p.id,p.department,p.doctor,p.status].join(' ').toLowerCase())}"><td>${rowPerson(p.name,`${p.age} years · ${p.gender}`)}</td><td>${esc(p.id)}</td><td>${esc(p.department)}</td><td>${esc(p.doctor)}</td><td>${esc(p.date)}</td><td>${badge(p.status)}</td>${actions?`<td><div class="action-cell"><button class="small-action" data-action="view-patient" data-id="${esc(p.id)}">View</button></div></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function patients(){return `${heading('Patients','Manage patient records and care journeys.',button('Add patient','new-patient',true,'+'))}<div class="grid stats-grid">${[['Registered patients',db.patients.length+1240],['Currently admitted',db.patients.filter(p=>p.status==='Admitted').length+86],['Appointments today',db.appointments.length+38],['Discharged this week','42']].map((x,i)=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${['i-blue','i-green','i-orange','i-purple'][i]}">${['♙','▤','▦','✓'][i]}</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot">Updated just now</div></div>`).join('')}</div><div class="card section-card"><div class="table-heading"><div><h2 class="card-title">All patients</h2><p class="card-subtitle">${db.patients.length} records · Changes save in this browser</p></div><div class="toolbar">${searchBox('Search patients...')}<select class="period-select" id="patient-filter"><option value="">All statuses</option><option>Admitted</option><option>Outpatient</option><option>Discharged</option></select></div></div><div id="patient-table">${patientTable(db.patients)}</div></div>`}
function genericTable(headers,rows,empty){return `<div class="table-scroll"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}"><div class="empty-state">${empty}</div></td></tr>`}</tbody></table></div>`}
function appointments(){let rows=db.appointments.map(a=>`<tr data-search-row="${esc([a.patient,a.doctor,a.department,a.status,a.id].join(' ').toLowerCase())}"><td>${esc(a.id)}</td><td>${rowPerson(a.patient,a.patientId)}</td><td>${esc(a.doctor)}</td><td>${esc(a.department)}</td><td>${esc(a.date)}</td><td>${esc(a.time)}</td><td>${esc(a.type)}</td><td>${badge(a.status)}</td><td><button class="small-action" data-action="toggle-appointment" data-id="${esc(a.id)}">${a.status==='Confirmed'?'Complete':'Update'}</button></td></tr>`);return `${heading('Appointments','Schedule and track patient visits.',button('Book appointment','new-appointment',true,'+'))}<div class="grid stats-grid">${[['Today',db.appointments.length+38],['Confirmed',db.appointments.filter(x=>x.status==='Confirmed').length+30],['Pending',db.appointments.filter(x=>x.status==='Pending').length+5],['Cancelled',db.appointments.filter(x=>x.status==='Cancelled').length+3]].map((x,i)=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${['i-blue','i-green','i-orange','i-purple'][i]}">▦</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot">Appointments</div></div>`).join('')}</div><div class="card section-card"><div class="table-heading"><div><h2 class="card-title">Appointment schedule</h2><p class="card-subtitle">Upcoming patient visits</p></div><div class="toolbar">${searchBox('Search schedule...')}<input class="period-select" type="date" aria-label="Filter by date" id="appointment-date" /></div></div><div id="appointment-table">${genericTable(['ID','Patient','Doctor','Department','Date','Time','Visit type','Status','Action'],rows,'No appointments yet.')}</div></div>`}
function staff(){let rows=db.staff.map(a=>`<tr data-search-row="${esc([a.name,a.role,a.department,a.status].join(' ').toLowerCase())}"><td>${rowPerson(a.name,a.id)}</td><td>${esc(a.role)}</td><td>${esc(a.department)}</td><td>${esc(a.email)}</td><td>${esc(a.phone)}</td><td>${badge(a.status)}</td><td><button class="small-action" data-action="toggle-staff" data-id="${esc(a.id)}">Update status</button></td></tr>`);return `${heading('Medical staff','Manage doctors and care team availability.',button('Add staff member','new-staff',true,'+'))}<div class="grid stats-grid">${[['Total staff',db.staff.length+124],['On duty',db.staff.filter(x=>x.status==='On duty').length+96],['On leave',db.staff.filter(x=>x.status==='On leave').length+8],['Departments','12']].map((x,i)=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${['i-blue','i-green','i-orange','i-purple'][i]}">♧</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot">Across all departments</div></div>`).join('')}</div><div class="card section-card"><div class="table-heading"><div><h2 class="card-title">Staff directory</h2><p class="card-subtitle">${db.staff.length} team members</p></div>${searchBox('Search staff...')}</div>${genericTable(['Staff member','Role','Department','Email','Phone','Availability','Action'],rows,'No staff match this search.')}</div>`}
function wards(){return `${heading('Wards & beds','Monitor occupancy and inpatient capacity.',button('Update bed status','ward-info',false,'▤'))}<div class="grid stats-grid">${[['Total beds',db.wards.reduce((a,w)=>a+w.total,0)],['Occupied',db.wards.reduce((a,w)=>a+w.occupied,0)],['Available',db.wards.reduce((a,w)=>a+w.total-w.occupied,0)],['Occupancy rate',`${Math.round(100*db.wards.reduce((a,w)=>a+w.occupied,0)/db.wards.reduce((a,w)=>a+w.total,0))}%`]].map((x,i)=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${['i-blue','i-orange','i-green','i-purple'][i]}">▤</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot">Live capacity overview</div></div>`).join('')}</div><div class="grid ward-grid section-card">${db.wards.map(w=>{let n=Math.round(100*w.occupied/w.total);return `<article class="card ward-card"><div class="ward-top"><div><h3>${esc(w.name)}</h3><div class="ward-meta">${esc(w.type)}</div></div>${badge(n>85?'High occupancy':'Available')}</div><div class="bed-row"><span>Bed occupancy</span><b>${w.occupied} / ${w.total}</b></div><div class="bed-track"><span style="width:${n}%;background:${n>85?'#e9a344':'#4c7def'}"></span></div><div class="bed-row"><span>${w.total-w.occupied} beds available</span><span>${n}% full</span></div></article>`}).join('')}</div>`}
function laboratory(){let rows=db.lab.map(a=>`<tr data-search-row="${esc([a.id,a.patient,a.test,a.status,a.priority].join(' ').toLowerCase())}"><td>${esc(a.id)}</td><td>${esc(a.patient)}</td><td>${esc(a.test)}</td><td>${esc(a.ordered)}</td><td>${badge(a.priority)}</td><td>${badge(a.status)}</td><td><button class="small-action" data-action="toggle-lab" data-id="${esc(a.id)}">${a.status==='Completed'?'View result':'Update'}</button></td></tr>`);return `${heading('Laboratory','Track diagnostic orders and test results.',button('New lab order','new-lab',true,'+'))}<div class="grid stats-grid">${[['Orders today',db.lab.length+32],['In progress',db.lab.filter(x=>x.status==='In progress').length+12],['Awaiting collection',db.lab.filter(x=>x.status==='Pending').length+8],['Results ready',db.lab.filter(x=>x.status==='Completed').length+12]].map((x,i)=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${['i-blue','i-orange','i-purple','i-green'][i]}">⚗</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot">Lab orders</div></div>`).join('')}</div><div class="card section-card"><div class="table-heading"><div><h2 class="card-title">Recent lab orders</h2><p class="card-subtitle">Patient diagnostics and test status</p></div>${searchBox('Search lab orders...')}</div>${genericTable(['Order ID','Patient','Test','Ordered','Priority','Status','Action'],rows,'No lab orders found.')}</div>`}
function pharmacy(){let rows=db.pharmacy.map(a=>`<tr data-search-row="${esc([a.name,a.category].join(' ').toLowerCase())}"><td>${esc(a.name)}</td><td>${esc(a.category)}</td><td>${a.stock}</td><td>${a.reorder}</td><td>${esc(a.expiry)}</td><td>${badge(a.stock<=a.reorder?'Low stock':'In stock')}</td><td><button class="small-action" data-action="restock" data-id="${esc(a.name)}">Restock</button></td></tr>`);return `${heading('Pharmacy','Monitor medication inventory and stock levels.',button('Add medication','new-medication',true,'+'))}<div class="grid stats-grid">${[['Products',db.pharmacy.length+348],['Low stock',db.pharmacy.filter(x=>x.stock<=x.reorder).length+12],['Prescriptions today','86'],['Expiring soon','7']].map((x,i)=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${['i-blue','i-orange','i-green','i-purple'][i]}">✣</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot">Inventory overview</div></div>`).join('')}</div><div class="card section-card"><div class="table-heading"><div><h2 class="card-title">Medication inventory</h2><p class="card-subtitle">Stock and expiry monitoring</p></div>${searchBox('Search inventory...')}</div>${genericTable(['Medication','Category','In stock','Reorder at','Expiry date','Status','Action'],rows,'No inventory found.')}</div>`}
function billing(){let rows=db.invoices.map(a=>`<tr data-search-row="${esc([a.id,a.patient,a.status].join(' ').toLowerCase())}"><td>${esc(a.id)}</td><td>${esc(a.patient)}</td><td>${esc(a.date)}</td><td>${currency(a.amount)}</td><td>${badge(a.status)}</td><td><button class="small-action" data-action="toggle-invoice" data-id="${esc(a.id)}">${a.status==='Paid'?'View':'Mark paid'}</button></td></tr>`);return `${heading('Billing & payments','Manage invoices, payment status, and revenue.',button('Create invoice','new-invoice',true,'+'))}<div class="grid stats-grid">${[['Revenue this month',currency(48250)],['Outstanding',currency(db.invoices.filter(x=>x.status!=='Paid').reduce((a,x)=>a+x.amount,0)+18640)],['Invoices paid',db.invoices.filter(x=>x.status==='Paid').length+312],['Overdue',db.invoices.filter(x=>x.status==='Overdue').length+8]].map((x,i)=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${['i-green','i-orange','i-blue','i-purple'][i]}">＄</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot">This month</div></div>`).join('')}</div><div class="card section-card"><div class="table-heading"><div><h2 class="card-title">Recent invoices</h2><p class="card-subtitle">${db.invoices.length} invoices</p></div>${searchBox('Search invoices...')}</div>${genericTable(['Invoice','Patient','Date','Amount','Status','Action'],rows,'No invoices found.')}</div>`}
function reports(){return `${heading('Reports & analytics','A snapshot of hospital performance.',`<select class="period-select"><option>Last 30 days</option><option>This quarter</option><option>This year</option></select>${button('Export report','export',true,'↓')}`)}<div class="grid stats-grid">${[['Patients seen','1,284','↑ 12.8%'],['Avg. wait time','18 min','↓ 4 min'],['Bed occupancy','76%','↑ 3.2%'],['Revenue',currency(48250),'↑ 14.6%']].map((x,i)=>`<div class="card stat-card"><div class="stat-top"><span class="stat-label">${x[0]}</span><span class="stat-icon ${['i-blue','i-green','i-orange','i-purple'][i]}">▥</span></div><div class="stat-value">${x[1]}</div><div class="stat-foot"><span class="trend">${x[2]}</span>vs previous period</div></div>`).join('')}</div><div class="grid wide-grid section-card">${[['Patient visits','1,284','Across outpatient and inpatient care'],['Top department','Emergency','318 visits this month'],['Patient satisfaction','94.8%','Based on 426 responses']].map(x=>`<div class="card info-card"><h3>${x[0]}</h3><div class="info-number">${x[1]}</div><p>${x[2]}</p></div>`).join('')}</div><div class="card section-card"><div class="card-header"><div><h2 class="card-title">Report center</h2><p class="card-subtitle">Export operational summaries for your selected period.</p></div></div><div class="department-row"><span class="department-icon i-blue">♙</span><span class="department-name">Patient activity report</span><button class="small-action" data-action="export">Export CSV</button></div><div class="department-row"><span class="department-icon i-green">＄</span><span class="department-name">Revenue and billing report</span><button class="small-action" data-action="export">Export CSV</button></div><div class="department-row"><span class="department-icon i-purple">▤</span><span class="department-name">Bed occupancy report</span><button class="small-action" data-action="export">Export CSV</button></div></div>`}
function settings(){let s=db.settings;return `${heading('Settings','Manage hospital details and system preferences.',button('Save changes','save-settings',true))}<div class="grid settings-grid"><div class="card settings-nav"><div class="settings-link active">Hospital profile</div><div class="settings-link" data-action="settings-notice">Preferences</div><div class="settings-link" data-action="settings-notice">Notifications</div><div class="settings-link" data-action="settings-notice">Security & access</div><div class="settings-link" data-action="settings-notice">Integrations</div></div><div class="card settings-form"><h2>Hospital profile</h2><p>Update your hospital's public and contact information.</p><div class="form-grid"><div class="field"><label for="setting-hospital">Hospital name</label><input id="setting-hospital" value="${esc(s.hospital)}" /></div><div class="field"><label for="setting-email">Contact email</label><input id="setting-email" type="email" value="${esc(s.email)}" /></div><div class="field"><label for="setting-phone">Phone number</label><input id="setting-phone" value="${esc(s.phone)}" /></div><div class="field"><label for="setting-currency">Currency</label><select id="setting-currency"><option>${esc(s.currency)}</option><option>USD ($)</option><option>GBP (£)</option></select></div><div class="field" style="grid-column:1/-1"><label for="setting-address">Address</label><input id="setting-address" value="${esc(s.address)}" /></div></div><div class="form-actions">${button('Save changes','save-settings',true)}</div></div></div>`}
const views={overview,patients,appointments,staff,wards,laboratory,pharmacy,billing,reports,settings};
function render(view=location.hash.slice(1)||'overview'){if(!views[view])view='overview';$('#page-content').innerHTML=views[view]();$('#patient-count').textContent=db.patients.length;$$('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.view===view));$('#breadcrumb-current').textContent=({overview:'Overview',patients:'Patients',appointments:'Appointments',staff:'Medical staff',wards:'Wards & beds',laboratory:'Laboratory',pharmacy:'Pharmacy',billing:'Billing',reports:'Reports',settings:'Settings'})[view];if(view==='overview')drawChart();}
function drawChart(){let c=$('#overview-chart');if(!c)return;let rect=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;let x=c.getContext('2d');x.scale(dpr,dpr);let w=rect.width,h=rect.height,p={l:30,r:8,t:8,b:23},cw=w-p.l-p.r,ch=h-p.t-p.b;x.font='9px DM Sans';x.fillStyle='#9aa6b7';x.textAlign='right';[0,25,50,75,100].forEach((n,i)=>{let y=p.t+ch*i/4;x.fillText(n,y+3);x.strokeStyle='#f0f2f6';x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke()});let labels=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],a=[42,65,52,78,60,87,72],b=[28,44,36,58,48,65,51];x.textAlign='center';labels.forEach((l,i)=>x.fillText(l,p.l+i*cw/6,h-4));function line(data,color){x.beginPath();data.forEach((v,i)=>{let xx=p.l+i*cw/6,yy=p.t+ch*(1-v/100);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.strokeStyle=color;x.lineWidth=2;x.stroke();data.forEach((v,i)=>{x.beginPath();x.arc(p.l+i*cw/6,p.t+ch*(1-v/100),2.5,0,Math.PI*2);x.fillStyle=color;x.fill()})}line(a,'#4c7def');line(b,'#46bd94')}
function openModal(title,fields,submitLabel,handler){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><form class="modal" id="data-form"><div class="modal-header"><h2>${title}</h2><button type="button" class="modal-close" aria-label="Close">×</button></div><div class="modal-body"><div class="form-grid">${fields.map(f=>`<div class="field" style="${f.wide?'grid-column:1/-1':''}"><label for="f-${f.name}">${f.label}</label>${f.options?`<select id="f-${f.name}" name="${f.name}" ${f.required===false?'':'required'}>${f.options.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`:`<input id="f-${f.name}" name="${f.name}" ${f.type?`type="${f.type}"`:''} ${f.required===false?'':'required'} placeholder="${f.placeholder||''}" />`}</div>`).join('')}</div><div class="form-actions"><button type="button" class="button modal-cancel">Cancel</button><button class="button button-primary">${submitLabel}</button></div></div></form></div>`;const close=()=>root.innerHTML='';$('.modal-close',root).onclick=close;$('.modal-cancel',root).onclick=close;$('.modal-backdrop',root).addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))close()});$('#data-form',root).onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));handler(data);close();save();render();};}
const departments=['Cardiology','Neurology','Pediatrics','Orthopedics','Emergency','General Medicine','Maternity'];
function newPatient(){openModal('Add patient',[{name:'name',label:'Full name',placeholder:'Patient full name'},{name:'age',label:'Age',type:'number'},{name:'gender',label:'Gender',options:['Female','Male','Other']},{name:'phone',label:'Phone number',type:'tel'},{name:'department',label:'Department',options:departments},{name:'doctor',label:'Assigned doctor',options:db.staff.map(x=>x.name)},{name:'blood',label:'Blood group',options:['Unknown','O+','O-','A+','A-','B+','B-','AB+','AB-']},{name:'status',label:'Patient status',options:['Outpatient','Admitted']}],'Save patient',d=>{let id=`PT-${1050+db.patients.length}`;db.patients.unshift({id,...d,age:+d.age||0,email:'',date:new Date().toISOString().slice(0,10)});db.activity.unshift({icon:'♙',tone:'i-blue',text:`<b>${esc(d.name)}</b> was added as a patient`,time:'Just now'});toast('Patient added successfully')})}
function newAppointment(){openModal('Book an appointment',[{name:'patient',label:'Patient name',options:db.patients.map(x=>x.name)},{name:'doctor',label:'Doctor',options:db.staff.filter(x=>x.role.toLowerCase().includes('doctor')||x.name.startsWith('Dr.')).map(x=>x.name)},{name:'department',label:'Department',options:departments},{name:'date',label:'Appointment date',type:'date'},{name:'time',label:'Appointment time',type:'time'},{name:'type',label:'Visit type',options:['Consultation','Follow-up','Check-up','Emergency']}],'Book appointment',d=>{let p=db.patients.find(x=>x.name===d.patient);db.appointments.unshift({id:`AP-${2306+db.appointments.length}`,...d,patientId:p?.id||'',status:'Confirmed'});db.activity.unshift({icon:'▦',tone:'i-green',text:`Appointment booked with <b>${esc(d.doctor)}</b>`,time:'Just now'});toast('Appointment booked')})}
function newStaff(){openModal('Add staff member',[{name:'name',label:'Full name'},{name:'role',label:'Role'},{name:'department',label:'Department',options:departments},{name:'email',label:'Email',type:'email'},{name:'phone',label:'Phone',type:'tel'}],'Add staff member',d=>{db.staff.unshift({id:`ST-${String(10+db.staff.length).padStart(3,'0')}`,...d,status:'On duty'});toast('Staff member added')})}
function newLab(){openModal('Create lab order',[{name:'patient',label:'Patient',options:db.patients.map(x=>x.name)},{name:'test',label:'Test name',placeholder:'e.g. Complete blood count'},{name:'priority',label:'Priority',options:['Routine','Urgent']}],'Create order',d=>{db.lab.unshift({id:`LB-${5005+db.lab.length}`,...d,ordered:new Date().toISOString().slice(0,10),status:'Pending'});toast('Lab order created')})}
function newMedication(){openModal('Add medication',[{name:'name',label:'Medication name'},{name:'category',label:'Category'},{name:'stock',label:'Opening stock',type:'number'},{name:'reorder',label:'Reorder level',type:'number'},{name:'expiry',label:'Expiry date',type:'date'}],'Add medication',d=>{db.pharmacy.unshift({...d,stock:+d.stock,reorder:+d.reorder});toast('Medication added to inventory')})}
function newInvoice(){openModal('Create invoice',[{name:'patient',label:'Patient',options:db.patients.map(x=>x.name)},{name:'amount',label:'Amount (CAD)',type:'number'},{name:'date',label:'Invoice date',type:'date'},{name:'status',label:'Status',options:['Unpaid','Paid']}],'Create invoice',d=>{db.invoices.unshift({id:`INV-${String(89+db.invoices.length).padStart(4,'0')}`,...d,amount:+d.amount});toast('Invoice created')})}
function exportData(){let view=location.hash.slice(1),list=view==='patients'?db.patients:view==='appointments'?db.appointments:view==='staff'?db.staff:view==='billing'?db.invoices:view==='pharmacy'?db.pharmacy:view==='laboratory'?db.lab:db.patients;let keys=[...new Set(list.flatMap(Object.keys))];let csv=[keys.join(','),...list.map(o=>keys.map(k=>`"${String(o[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`carepoint-${view||'report'}.csv`;a.click();URL.revokeObjectURL(a.href);toast('Report exported as CSV')}
function action(act,id){if(act==='new-patient')return newPatient();if(act==='new-appointment')return newAppointment();if(act==='new-staff')return newStaff();if(act==='new-lab')return newLab();if(act==='new-medication')return newMedication();if(act==='new-invoice')return newInvoice();if(act==='export')return exportData();if(act==='wards')return setView('wards');if(act==='save-settings'){db.settings={hospital:$('#setting-hospital').value,email:$('#setting-email').value,phone:$('#setting-phone').value,address:$('#setting-address').value,currency:$('#setting-currency').value};save();toast('Hospital settings saved');return}if(act==='settings-notice')return toast('This settings section is coming soon.');if(act==='activity')return toast('You are viewing the latest activity.');if(act==='help')return toast('Help center: support@carepoint.health');if(act==='notifications')return toast('You’re all caught up.');if(act==='ward-info')return toast('Bed availability is updated from patient admissions.');if(act==='view-patient'){let p=db.patients.find(x=>x.id===id);return toast(`${p.name} · ${p.department} · ${p.status}`)}if(act==='toggle-appointment'){let x=db.appointments.find(a=>a.id===id);x.status=x.status==='Confirmed'?'Completed':'Confirmed';save();return render()}if(act==='toggle-staff'){let x=db.staff.find(a=>a.id===id);x.status=x.status==='On duty'?'On leave':'On duty';save();return render()}if(act==='toggle-lab'){let x=db.lab.find(a=>a.id===id);if(x.status!=='Completed')x.status=x.status==='Pending'?'In progress':'Completed';save();return render()}if(act==='toggle-invoice'){let x=db.invoices.find(a=>a.id===id);if(x.status!=='Paid')x.status='Paid';save();return render()}if(act==='restock'){let x=db.pharmacy.find(a=>a.name===id);x.stock+=50;save();render();return toast('50 units added to stock')}}
document.addEventListener('click',e=>{let nav=e.target.closest('[data-view]');if(nav){e.preventDefault();setView(nav.dataset.view);return}let a=e.target.closest('[data-action]');if(a){action(a.dataset.action,a.dataset.id);return}});
document.addEventListener('input',e=>{if(e.target.matches('[data-table-search]')){let q=e.target.value.toLowerCase();$$('[data-search-row]').forEach(r=>r.style.display=r.dataset.searchRow.includes(q)?'':'none')}});
document.addEventListener('change',e=>{if(e.target.id==='patient-filter'){let v=e.target.value;let arr=db.patients.filter(p=>!v||p.status===v);$('#patient-table').innerHTML=patientTable(arr)}if(e.target.id==='appointment-date'&&e.target.value){let date=e.target.value;$$('#appointment-table [data-search-row]').forEach(r=>r.style.display=r.dataset.searchRow.includes(date)?'':'none')}});
$('#global-search').addEventListener('keydown',e=>{if(e.key==='Enter'){let v=e.target.value.trim().toLowerCase();let page=db.patients.some(p=>`${p.name} ${p.id}`.toLowerCase().includes(v))?'patients':db.appointments.some(a=>`${a.patient} ${a.id}`.toLowerCase().includes(v))?'appointments':db.staff.some(s=>s.name.toLowerCase().includes(v))?'staff':'patients';setView(page);let search=$('[data-table-search]');if(search){search.value=e.target.value;search.dispatchEvent(new Event('input',{bubbles:true}))}}});
$('#menu-button').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#help-button').addEventListener('click',()=>toast('Help center: support@carepoint.health'));$('#notification-button').addEventListener('click',()=>toast('You’re all caught up.'));window.addEventListener('hashchange',()=>render());window.addEventListener('resize',()=>drawChart());render();
